{
 "title": "VXLAN",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "L2ROUTE Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fabric2-leaf2",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "l2route_seq_number{job=\"fabric2-leaf2\"}"
    }
   ]
  },
  {
   "title": "fabric2-bgw2",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "l2route_seq_number{job=\"fabric2-bgw2\"}"
    }
   ]
  },
  {
   "title": "fabric1-leaf2",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "l2route_seq_number{job=\"fabric1-leaf2\"}"
    }
   ]
  },
  {
   "title": "fabric1-bgw1",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "l2route_seq_number{job=\"fabric1-bgw1\"}"
    }
   ]
  },
  { "title": "MAC/IP Per VLANs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "fabric2-leaf1 - Vlan 2100",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "l2route_seq_number{job=\"fabric2-leaf1\",vlan=\"2100\"}",
     "legendFormat": "{{mac}} - {{ip}}"
    }
   ]
  },
  {
   "title": "fabric2-leaf1 - Vlan 2110",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "l2route_seq_number{job=\"fabric2-leaf1\",vlan=\"2110\"}",
     "legendFormat": "{{mac}} - {{ip}}"
    }
   ]
  },
  { "title": "VXLAN VRF Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "fabric2-leaf1",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "vni_state{job=\"fabric2-leaf1\",type=\"L3\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "fabric2-leaf2",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "vni_state{job=\"fabric2-leaf2\",type=\"L3\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "VXLAN VLAN Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "fabric2-leaf1",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "vni_state{job=\"fabric2-leaf1\",type=\"L2\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "fabric2-leaf2",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "vni_state{job=\"fabric2-leaf2\",type=\"L2\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}