{
 "title": "IP Prefix Tracking",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Raw Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fabric1-bgw1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ip_prefix_path_traffic{job=\"fabric1-bgw1\",family=\"unicast\",interface=~\"Eth1/49|Eth1/52\"}"
    }
   ]
  },
  {
   "title": "fabric2-bgw2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ip_prefix_path_traffic{job=\"fabric2-bgw2\",family=\"unicast\"}"
    }
   ]
  },
  {
   "title": "fabric2-leaf1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ip_prefix_path_traffic{job=\"fabric2-leaf1\",family=\"unicast\"}"
    }
   ]
  },
  {
   "title": "fabric2-leaf2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ip_prefix_path_traffic{job=\"fabric2-leaf2\",family=\"unicast\"}"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "fabric1-bgw1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ip_prefix_path_traffic{job=\"fabric1-bgw1\",family=\"unicast\"}[5m])"
    }
   ]
  },
  {
   "title": "fabric2-bgw2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ip_prefix_path_traffic{job=\"fabric2-bgw2\",family=\"unicast\"}[5m])"
    }
   ]
  },
  {
   "title": "fabric2-leaf1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ip_prefix_path_traffic{job=\"fabric2-leaf1\",family=\"unicast\"}[5m])"
    }
   ]
  },
  {
   "title": "fabric2-leaf2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ip_prefix_path_traffic{job=\"fabric2-leaf2\",family=\"unicast\"}[5m])"
    }
   ]
  },
  { "title": "Prefix Next Hop Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "fabric1-bgw1 (Last Day Changes)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "delta(ip_prefix_path_count{job=\"fabric1-bgw1\",vrf=\"default\"}[1d])",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "fabric1-bgw1 (Current Count)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "ip_prefix_path_count{job=\"fabric1-bgw1\",vrf=\"default\"}",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "fabric2-bgw2 (Last Hour Changes)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "delta(ip_prefix_path_count{job=\"fabric2-bgw2\",vrf=\"default\"}[1h])",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "fabric2-bgw2 (Current Count)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "ip_prefix_path_count{job=\"fabric2-bgw2\",vrf=\"default\"}",
     "legendFormat": "{{prefix}}"
    }
   ]
  }
 ]
}